name: Build Applications

on:
  push:
    branches:
      - main  # 빌드하고자 하는 브랜치로 변경

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine changed directories
        id: changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          grep -Eo '(frontend|user|order|store)' changed_files.txt > changed_apps.txt || echo "No changes"
          cat changed_apps.txt

      - name: Build and deploy changed apps
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-2  # 배포하고자 하는 리전으로 변경
        run: |
          cat changed_apps.txt | while read app; do
            if [ -d "$app" ]; then
              cd $app
              # 각 어플리케이션 빌드 및 배포 작업 수행
              # 예: npm install, npm build, aws s3 sync 등의 명령어 실행
              cd ..
            fi
          done
