name: Build Applications

on:
  push:
    branches:
      - main  # 빌드하고자 하는 브랜치로 변경

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Determine changed directories
        id: changes
        run: |
          git fetch
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          grep -Eo '(frontend|user|order|store)' changed_files.txt > changed_apps.txt || echo "No changes"
          cat changed_apps.txt

      - name: Build and push Docker images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cat changed_apps.txt | while read app; do
            if [ -d "$app" ]; then
              cd $app
              docker build -t $ECR_REGISTRY/${app}-app:$GITHUB_SHA .
              docker push $ECR_REGISTRY/${app}-app:$GITHUB_SHA
              cd ..
            fi
          done
